import "./globals.css";
import { Poppins } from "next/font/google";
import { Providers } from "../../components/Providers";

export const poppins = Poppins({ weight: "700", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="root" style={{ maxWidth: 1152, marginInline: "auto" }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
